---
author: "Ryan Bolen"
title: "Clean Data"
format: 
  docx: 
    echo: true
    message: false
editor: visual
---

## Libraries

In the following code chunk, load all the libraries you will need:

```{r}
library(tidyverse)
library(fixest)
library(rio)
library(lubridate)
library(ggplot2)


```

```{r}
# Getting all trends up to files in a list to pass to import/merge.

trends_up_to_list <- list.files(pattern = 'trends_up_to_')

```

```{r}
trends_up_to <- import_list(trends_up_to_list,rbind = TRUE, fill = TRUE)
```

```{r}
# Get the first ten characters out of the month or week column which at the moment is a string. 

# Change the date string to an actual date and then floor it to the first day of the month.

trends_up_to <- trends_up_to %>% 
  mutate(monthorweek2 = str_sub(monthorweek,end = 10)) %>% 
  mutate(monthorweek2 = ymd(monthorweek2)) %>% 
  mutate(first_day_of_month = floor_date(monthorweek2,unit= 'month'))

```

```{r}

# Standardize the index variable by school name

trends_up_to <- trends_up_to %>% group_by(schname,keyword) %>% mutate(std_key = (index -mean(index,na.rm = TRUE))/sd(index,na.rm = TRUE))
```

```{r}

# Summarize to school name and month level

trends_up_to <- trends_up_to %>% group_by(first_day_of_month,schname) %>% summarize(tot = sum(std_key))
```

```{r}

# Read in the scorecard data

SC <- import('Most+Recent+Cohorts+(Scorecard+Elements).csv')

# Read in the id name link data

id_name_link <- import('id_name_link.csv')
```

```{r}
# count how many times each school name pops up in id_name_link filter out any rows where n > 1

id_name_link <- id_name_link %>% group_by(schname) %>% mutate(n = n()) %>% filter(n == 1)

```

```{r}
# Merge data sets - inner join trends up to (D2) on id_name_link that we summarised.

trends_up_to <- trends_up_to %>% inner_join(id_name_link, join_by(schname)) 

SC <- SC %>% mutate(opeid = OPEID)

clean_data <- trends_up_to %>% inner_join(SC, join_by(opeid))


```

```{r}
# Need to look at data before September 2015 (before card was released) and after September 2015 (after it was released)

# Vars that might be good to control for:

# Admission Rate 'ADM_RATE'
# Percentage of students who are financially independent 'DEP_STAT_PCT_IND' - CANNNOT FIND
# Dependent Variable of choice - CANNOT FIND
# Mean earnings of students working and not enrolled 10 years after entry 'mn_earn_wne_p10'
# Graduation rate (on time is considered 6 years) - C150_4_POOLED_SUPP-REPORTED-GRAD-RATE
# Annual cost of going (average) - NPT4_PUB-AVERAGE-ANNUAL-COST

# a one-unit change in the standardized index can be understood and interpreted as a one-standard-deviation change in search interest



```

```{r}

# Getting frame with only colleges that grant bachelor's degrees using PREDDEG variable equal to 3

bach_degree_school_data <- clean_data

bach_degree_school_data <- clean_data %>% filter(PREDDEG == 3)

bach_degree_school_data <- bach_degree_school_data %>% select(first_day_of_month,`md_earn_wne_p10-REPORTED-EARNINGS`,schname,tot,unitid,opeid,PREDDEG,`C150_4_POOLED_SUPP-REPORTED-GRAD-RATE`,`NPT4_PUB-AVERAGE-ANNUAL-COST`)

bach_degree_school_data <- bach_degree_school_data %>% mutate(mnth = month(first_day_of_month))

# Filter to only get schools where med earnings is reported

bach_degree_school_data <- bach_degree_school_data %>% filter(`md_earn_wne_p10-REPORTED-EARNINGS` != 'PrivacySuppressed')

bach_degree_school_data <- bach_degree_school_data %>% filter(`md_earn_wne_p10-REPORTED-EARNINGS` != 'NULL')


# Variable for high earnings and low earnings school - used 75K (might change to 75th percentile)

median_earnings <- 48100

# Changing earnings to numeric

bach_degree_school_data <- bach_degree_school_data %>% mutate(earnings = as.numeric(`md_earn_wne_p10-REPORTED-EARNINGS`))

# Creating a var to call out high and low earnings schools

bach_degree_school_data <- bach_degree_school_data %>% mutate(high_earnings_school = earnings >= median_earnings)

```

```{r}
# Creating a var for before and after scorecard (first day of month greater or equal to september 2015)

bach_degree_school_data <- bach_degree_school_data %>% mutate(after_sc = ymd(first_day_of_month) >= ymd('2015-09-01'))

quantile(bach_degree_school_data$earnings,type= 9)

```

```{r}
model1 <- feols(tot~after_sc,data = bach_degree_school_data)
etable(model1)
```

```{r}
#(dependent) = (independent) + (control1) + (control2)
# tot = score_card_introduced 
```
